name: Build OriginalPoster Plugin

on:
  push:
    branches: [ "main", "cd*" ]
  pull_request:
    branches: [ "main" , "cd*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup.NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: EverMedia-Plugin
        # path: ./bin/Release/netstandard2.0/EverMedia.dll
        path: ./bin/Release/net8.0/OriginalPoster.dll
